name: mw-mt6

task_name: mw-mt6
lazy_eval: False

shape_meta: &shape_meta
  obs:
    corner2_rgb:
      shape: [3, 128, 128]
      type: rgb
    behindGripper_rgb:
      shape: [3, 128, 128]
      type: rgb
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [4]


env_runner:
  _target_: diffusion_policy.env_runner.metaworld_runner.MetaworldRunner
  task_name: mt6
  n_test: 100
  n_test_vis: 10
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_parallel_envs: 20
  num_points: 512
  image_size: 128
  camera_names: ['corner2', 'behindGripper']
  video_camera: 'corner2'
  max_episode_steps: 200


dataset:
  _target_: diffusion_policy.dataset.metaworld_dataset.MetaworldDataset
  zarr_path: data/metaworld/mt6_expert_${training.num_demo}.zarr
  obs_keys:
    - corner2_rgb
    - behindGripper_rgb
    - agent_pos
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.1
  